[tool.poetry]
name = "menura-backend"
version = "2.0.0"
description = "Menura 2.0 - Asistente Personal y Segundo Cerebro con RAG Híbrido (Vector+Graph)"
authors = ["MASG", "ARM"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
websockets = "^12.0"
faster-whisper = "^1.0.2"
lancedb = "^0.8.0"
kuzu = "^0.4.2"
pydantic = "^2.7.4"
pyyaml = "^6.0.1"
numpy = "1.26.4"
openai = "^1.35.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
